spring.application.name=SoapRestApi
project.version = 1.0.0
spring.datasource.url=jdbc:postgresql://localhost:5432/soap_rest_api
spring.datasource.username=postgres
spring.datasource.password=ProgramHack
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false